const blankMeta = { sourceName: "", sourceUrl: "", sourceType: "", author: "", publishedAt: "", imageUrl: "", imageAlt: "", imageCredit: "", imageSourceUrl: "", visualImportance: 0, relatedTags: [], relatedContentIds: [] };
const item = (data) => ({ subCategory: "", language: "", contentType: "Article", difficulty: "", what: "", why: "", takeaway: "", aiNote: "", tags: [], ...blankMeta, ...data });

const mvpContent = [
  item({ id: "today-ai-commerce", page: "today", category: "AI", subCategory: "E-commerce", contentType: "Focus", title: "小红书店铺开始把 AI 图文当成日常货架能力", summary: "AI product imagery is moving from campaign novelty into everyday shelf work: scene images, title tests, and FAQ support.", what: "Small stores are using AI to produce product-context content faster.", why: "When production gets cheaper, taste, selection, and consistency become the real advantage.", takeaway: "Watch how tool efficiency becomes brand memory, not just faster output.", aiNote: "Look at the operating judgment behind the AI output, not only whether the generated image looks real.", tags: ["AI", "e-commerce", "self-media"], sourceName: "Shopify App Store: Shoppulse PhotoAI", sourceUrl: "https://apps.shopify.com/shoppulse", sourceType: "app listing", author: "ShopPulse", publishedAt: "2026-03-11", relatedTags: ["product page", "visual system"] }),
  item({ id: "today-khh-producer-tag", page: "today", category: "K-Hiphop", subCategory: "Music", contentType: "Fresh Find", title: "Producer tag 正在变成短视频记忆点", summary: "A producer tag can put listeners into a track's world in two seconds, especially when clips travel through short video.", what: "Producer identity is becoming a recognizable sonic marker.", why: "It connects track, maker, and shareable moment.", takeaway: "Treat the tag like a sound logo when studying K-Hiphop spread.", aiNote: "Useful as culture context, but an image would not explain this better than listening would.", tags: ["K-Hiphop", "sound identity", "culture"], sourceName: "Wikipedia: GroovyRoom", sourceUrl: "https://en.wikipedia.org/wiki/GroovyRoom", sourceType: "artist reference", author: "Wikipedia contributors" }),
  item({ id: "today-packaging-system", page: "today", category: "Design", subCategory: "Packaging", contentType: "Fresh Find", title: "低饱和包装不等于“性冷淡”", summary: "K-beauty packaging often uses muted color, narrow text columns, and material contrast to make information feel breathable.", what: "Visual calm can still carry rich product information.", why: "Shelf and product-page decisions both depend on quick trust signals.", takeaway: "Study hierarchy, spacing, and material cues before collecting palettes.", aiNote: "This is visual, so a real packaging image helps you inspect the point directly.", tags: ["design", "packaging", "K-brand"], sourceName: "Wikimedia Commons: Box of Korean cosmetics", sourceUrl: "https://commons.wikimedia.org/wiki/File:Box_of_Korean_cosmetics.jpg", sourceType: "image reference", author: "Teemeah", publishedAt: "2016-11-28", imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Box_of_Korean_cosmetics.jpg?width=960", imageAlt: "A box of Innisfree green tea line cosmetic products showing green packaging and grouped skincare containers.", imageCredit: "Teemeah, CC BY-SA 3.0, via Wikimedia Commons", imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Box_of_Korean_cosmetics.jpg", visualImportance: 2 }),

  item({ id: "obs-self-xhs-search", page: "observe", category: "Self-media", subCategory: "Xiaohongshu", title: "小红书笔记越来越像搜索结果页", summary: "Strong posts answer a precise search intent before showing personality.", what: "Creators structure posts around questions, comparison, and proof.", why: "Search-driven discovery rewards clarity over vague lifestyle posting.", takeaway: "Write the first screen like an answer, then add voice.", tags: ["self-media", "Xiaohongshu", "search"] }),
  item({ id: "obs-self-instagram-carousel", page: "observe", category: "Self-media", subCategory: "Instagram", title: "Instagram carousel is becoming a mini editorial format", summary: "Carousels work best when each slide advances one argument, not when it repeats the same headline.", what: "Swipe structure creates a reading rhythm.", why: "It lets creators teach without asking for a long read upfront.", takeaway: "Plan carousel slides as claims, evidence, example, and save-worthy close.", tags: ["Instagram", "editorial", "content strategy"], sourceName: "Wikipedia: Instagram", sourceUrl: "https://en.wikipedia.org/wiki/Instagram", sourceType: "platform reference", author: "Wikipedia contributors" }),
  item({ id: "obs-self-youtube-retention", page: "observe", category: "Self-media", subCategory: "YouTube", title: "YouTube intros are moving from greeting to contract", summary: "Better intros quickly say what the viewer will understand by the end.", what: "Opening lines are becoming clearer promises.", why: "Viewers decide fast whether a video respects their time.", takeaway: "Lead with the learning contract, then show personality.", tags: ["YouTube", "retention", "creator work"], sourceName: "Wikipedia: YouTube", sourceUrl: "https://en.wikipedia.org/wiki/YouTube", sourceType: "platform reference", author: "Wikipedia contributors" }),
  item({ id: "obs-self-content-pillars", page: "observe", category: "Self-media", subCategory: "Content strategy", title: "Content pillars should behave like lenses, not boxes", summary: "Rigid pillars make accounts repetitive; useful lenses let one topic connect to several audience needs.", what: "Creators are organizing by audience job, not just format.", why: "This keeps consistency without flattening curiosity.", takeaway: "Name the lens: learn, compare, decide, apply, or collect.", tags: ["content strategy", "creator business", "positioning"] }),
  item({ id: "obs-self-creator-business", page: "observe", category: "Self-media", subCategory: "Creator business", title: "Creator products need explanation before persuasion", summary: "Templates, courses, and guides convert better when the problem and fit are clear.", what: "Digital product pages are borrowing article-like structure.", why: "The user must know whether the product is for them before caring about price.", takeaway: "Explain use case, owner, boundary, and outcome before selling.", tags: ["creator business", "product page", "trust"] }),

  item({ id: "obs-design-packaging", page: "observe", category: "Design", subCategory: "Packaging", title: "Packaging trust is built through hierarchy", summary: "Good packaging lets the eye find brand, product type, key benefit, and proof without hunting.", what: "Information order is doing emotional work.", why: "Trust often comes from not feeling confused.", takeaway: "Map the first three things the package asks you to read.", tags: ["design", "packaging", "trust"], visualImportance: 1 }),
  item({ id: "obs-design-typography", page: "observe", category: "Design", subCategory: "Typography", title: "Hangeul typography carries cultural rhythm", summary: "Hangeul lettering can signal era, tone, and brand category through grouping and spacing.", what: "Letterforms are used as cultural surface and navigation.", why: "Typography is often the fastest way to feel whether a reference is modern, nostalgic, or premium.", takeaway: "Study spacing and grouping, not only the font name.", tags: ["typography", "Hangeul", "branding"], sourceName: "National Hangeul Museum", sourceUrl: "https://m.hangeul.go.kr/lang/en/html/traceHangeul/traceHangeul32.do", sourceType: "museum reference", author: "National Hangeul Museum", visualImportance: 1 }),
  item({ id: "obs-design-branding", page: "observe", category: "Design", subCategory: "Branding", title: "Quiet branding still needs one memorable signal", summary: "Minimal systems fail when every element becomes equally quiet.", what: "Brands need a specific shape, rhythm, color, or phrase to remember.", why: "Recognition depends on contrast, not decoration.", takeaway: "Ask what one thing remains recognizable when the layout changes.", tags: ["branding", "visual system", "memory"] }),
  item({ id: "obs-design-editorial", page: "observe", category: "Design", subCategory: "Editorial design", title: "Editorial layout lowers reading pressure", summary: "Whitespace, short decks, and clear section rhythm make dense topics feel approachable.", what: "Layout becomes a reading aid.", why: "Good hierarchy protects attention before the content begins.", takeaway: "Use spacing to say what matters first.", tags: ["editorial", "layout", "reading"] }),
  item({ id: "obs-design-ui", page: "observe", category: "Design", subCategory: "Web/UI", title: "Useful UI feels calm because choices are bounded", summary: "Dense tools can still feel quiet when each screen has a clear primary job.", what: "Interfaces are reducing visible options per moment.", why: "Fewer simultaneous decisions makes repeated use easier.", takeaway: "Design around the next action, not all possible actions.", tags: ["UI", "web design", "product"] }),

  item({ id: "obs-khh-music", page: "observe", category: "K-Hiphop", subCategory: "Music", title: "K-Hiphop hooks often start before the chorus", summary: "Texture, tag, ad-lib, and first bar can all become the remembered hook.", what: "The hook is not only melodic.", why: "Short clips reward immediate identity.", takeaway: "Listen for the first recognizable sound, not just the chorus.", tags: ["K-Hiphop", "music", "hook"] }),
  item({ id: "obs-khh-culture", page: "observe", category: "K-Hiphop", subCategory: "Culture", title: "Crew identity still matters in solo-first listening", summary: "Even when users discover tracks individually, crew and label context explains taste clusters.", what: "Social context shapes sound perception.", why: "It helps listeners connect producers, features, and aesthetics.", takeaway: "Track relationships, not only artists.", tags: ["K-Hiphop", "culture", "crew"] }),
  item({ id: "obs-khh-industry", page: "observe", category: "K-Hiphop", subCategory: "Industry", title: "Festival lineups reveal audience bridges", summary: "Shared stages show which artists are being positioned for overlapping listeners.", what: "Lineups are market maps.", why: "They show how scenes create adjacency.", takeaway: "Read billing order and pairings as industry signals.", tags: ["K-Hiphop", "industry", "festival"] }),
  item({ id: "obs-khh-visual", page: "observe", category: "K-Hiphop", subCategory: "Visual design", title: "Cover art is moving toward editorial restraint", summary: "Photography, narrow type, and softer contrast can make releases feel more lifestyle-driven.", what: "Visual language is less poster-like in some releases.", why: "It travels better across thumbnails, feeds, and merch.", takeaway: "Compare cover art at thumbnail size first.", tags: ["K-Hiphop", "cover art", "design"], visualImportance: 1 }),
  item({ id: "obs-khh-language", page: "observe", category: "K-Hiphop", subCategory: "Language", title: "Lyrics teach register more than dictionary meaning", summary: "Slang, honorific dropping, and address terms reveal stance and identity.", what: "Language choices position the speaker.", why: "Translation misses tone when it only carries meaning.", takeaway: "Annotate who is speaking to whom, and with what distance.", tags: ["K-Hiphop", "lyrics", "Korean"] }),

  item({ id: "obs-ai-workflow", page: "observe", category: "AI", subCategory: "Workflow", title: "AI workflow value starts with task boundaries", summary: "The useful question is what the tool should do, stop doing, and hand back to the user.", what: "Boundaries are becoming product quality.", why: "Users trust tools that know when not to continue.", takeaway: "Define the handoff before optimizing prompts.", tags: ["AI", "workflow", "product"] }),
  item({ id: "obs-ai-tool", page: "observe", category: "AI", subCategory: "Tool", title: "Single-purpose AI tools are easier to evaluate", summary: "A narrow image, note, or research tool can be judged by output quality faster than a broad assistant.", what: "AI tools are specializing around workflows.", why: "Specific jobs make quality visible.", takeaway: "Evaluate by repeated use, not demo surprise.", tags: ["AI", "tool", "evaluation"] }),
  item({ id: "obs-ai-product", page: "observe", category: "AI", subCategory: "Product", title: "AI UI should expose confidence and source trail", summary: "Users need to know what is inferred, what is sourced, and what remains uncertain.", what: "Transparency is becoming interface work.", why: "It prevents generated text from feeling like unsupported authority.", takeaway: "Show provenance in secondary UI, not as a wall of caveats.", tags: ["AI", "product", "source"] }),
  item({ id: "obs-ai-industry", page: "observe", category: "AI", subCategory: "Industry", title: "AI adoption is becoming operational, not just experimental", summary: "Teams are moving from demos toward repeatable internal processes.", what: "AI is entering everyday operations.", why: "Process fit matters more than feature novelty.", takeaway: "Ask what job changed this week, not what model launched.", tags: ["AI", "industry", "operations"] }),
  item({ id: "obs-ai-case", page: "observe", category: "AI", subCategory: "Case study", title: "AI product photography is useful when constraints are explicit", summary: "Generated images work better when brand palette, angle, material, and use case are bounded.", what: "Prompting becomes art direction.", why: "Visual consistency depends on constraints.", takeaway: "Write image briefs like design briefs.", tags: ["AI", "case study", "product photography"] }),

  item({ id: "obs-ecom-product-page", page: "observe", category: "E-commerce", subCategory: "Product page", title: "Product pages are becoming explanation pages", summary: "Good pages identify problem, fit, proof, and next action before pushing urgency.", what: "Commerce copy is absorbing editorial structure.", why: "Understanding reduces hesitation.", takeaway: "Make the user feel oriented before asking them to buy.", tags: ["e-commerce", "product page", "copywriting"] }),
  item({ id: "obs-ecom-content-commerce", page: "observe", category: "E-commerce", subCategory: "Content commerce", title: "Content commerce works when the content still stands alone", summary: "Posts that only push products feel thin; useful context creates trust first.", what: "Content and commerce are merging.", why: "Users resist sales without understanding.", takeaway: "Give a useful lens before the product link.", tags: ["e-commerce", "content commerce", "trust"] }),
  item({ id: "obs-ecom-trust", page: "observe", category: "E-commerce", subCategory: "Customer trust", title: "Trust cues are more than reviews", summary: "Sizing clarity, return rules, ingredient explanations, and comparison photos all reduce risk.", what: "Trust is built across small details.", why: "Unanswered doubt blocks conversion.", takeaway: "List the doubts a buyer has before adding persuasion.", tags: ["e-commerce", "trust", "conversion"] }),
  item({ id: "obs-ecom-branding", page: "observe", category: "E-commerce", subCategory: "Branding", title: "Marketplace brands need memory beyond price", summary: "A repeatable visual or verbal system helps a product survive comparison shopping.", what: "Brand assets are becoming conversion assets.", why: "Price-only positioning is fragile.", takeaway: "Find the repeatable cue that remains after the discount disappears.", tags: ["e-commerce", "branding", "marketplace"] }),
  item({ id: "obs-ecom-conversion", page: "observe", category: "E-commerce", subCategory: "Conversion experience", title: "Conversion improves when decisions are sequenced", summary: "Asking users to pick variant, trust seller, compare benefits, and pay at once creates friction.", what: "Good commerce UX stages decisions.", why: "Reduced cognitive load can be as valuable as stronger copy.", takeaway: "Separate selection, proof, and purchase moments.", tags: ["e-commerce", "UX", "conversion"] })
];

const lesson = (data) => ({ id: "", page: "language", category: "Language", subCategory: "", language: "English", contentType: "Expression", difficulty: "Intermediate", title: "", expression: "", phrase: "", translation: "", summary: "", explanation: "", realContext: "", usage: "", whenNotToUse: "", words: [], grammarPoints: [], aiNote: "", tags: [], ...blankMeta, ...data });
const mvpLessons = [
  lesson({ id: "en-shaping-idea", language: "English", contentType: "Expression", difficulty: "Intermediate", title: "I'm still shaping the idea.", expression: "I'm still shaping the idea.", translation: "我还在把这个想法整理成型。", summary: "A natural way to show uncertainty as active thinking.", explanation: "Shape suggests you are forming the structure, not simply lacking an answer.", realContext: "Design discussion, content planning, business ideas.", usage: "Use when an idea exists but is not ready to present as final.", whenNotToUse: "Avoid when you have no idea at all or when a direct answer is required.", words: [["shape", "to influence or give form to an idea"]], aiNote: "This is useful for creator work because it protects unfinished thinking without sounding passive.", tags: ["Expression", "creator work"], sourceName: "Cambridge Dictionary: shape", sourceUrl: "https://dictionary.cambridge.org/us/dictionary/english/shape", sourceType: "dictionary", author: "Cambridge University Press" }),
  lesson({ id: "en-nuance-not-quite", language: "English", contentType: "Nuance", difficulty: "Intermediate", title: "not quite vs not really", expression: "It's not quite what I meant.", translation: "这不完全是我的意思。", summary: "A softer correction than saying something is wrong.", explanation: "Not quite points to precision; not really often rejects the whole idea.", realContext: "Feedback, editing, collaboration.", usage: "Use when someone is close but the meaning needs adjustment.", whenNotToUse: "Avoid if the issue is serious and needs direct correction.", tags: ["Nuance", "feedback"] }),
  lesson({ id: "en-collocation-build-on", language: "English", contentType: "Collocation", difficulty: "Intermediate", title: "build on an idea", expression: "Can I build on that?", translation: "我可以接着这个想法往下说吗？", summary: "A collaborative phrase for meetings and brainstorming.", explanation: "Build on means extend rather than replace.", realContext: "Creator meetings, class discussion, interviews.", usage: "Use before adding a related point.", whenNotToUse: "Avoid when you are actually disagreeing sharply.", tags: ["Collocation", "business"] }),
  lesson({ id: "en-internet-lowkey", language: "English", contentType: "Internet", difficulty: "Intermediate", title: "low-key", expression: "I'm low-key obsessed with this layout.", translation: "我有点暗暗喜欢这个版式。", summary: "A casual way to soften enthusiasm.", explanation: "Low-key makes the emotion feel less dramatic or more casual.", realContext: "Internet comments, friends, informal creator notes.", usage: "Use in casual speech or social captions.", whenNotToUse: "Avoid in formal writing or exams.", tags: ["Internet", "tone"] }),
  lesson({ id: "en-grammar-would-rather", language: "English", contentType: "Grammar", difficulty: "Intermediate", title: "would rather for preference", expression: "I'd rather make it clearer than make it louder.", translation: "我宁愿让它更清楚，而不是更抢眼。", summary: "A practical structure for design and strategy preferences.", explanation: "Would rather contrasts priorities without sounding absolute.", realContext: "Design feedback, product decisions.", usage: "Use to state a preferred direction.", whenNotToUse: "Avoid if the decision has already been finalized.", grammarPoints: ["would rather + verb", "than + verb"], tags: ["Grammar", "design"] }),
  lesson({ id: "en-business-scope", language: "English", contentType: "Business", difficulty: "Upper-intermediate", title: "scope creep", expression: "This is starting to become scope creep.", translation: "这开始有点范围蔓延了。", summary: "A concise way to name uncontrolled expansion.", explanation: "Scope creep means new requirements keep entering the work beyond the original plan.", realContext: "Projects, freelance work, product meetings.", usage: "Use when protecting focus and timeline.", whenNotToUse: "Avoid using it as a blunt refusal without explanation.", tags: ["Business", "project"] }),
  lesson({ id: "en-practical-pushback", language: "English", contentType: "Expression", difficulty: "Upper-intermediate", title: "gentle pushback", expression: "I see the point, but I'm not sure it solves the core problem.", translation: "我理解这个点，但不确定它解决了核心问题。", summary: "A balanced way to disagree while keeping the discussion constructive.", explanation: "It acknowledges before redirecting to the main issue.", realContext: "Team discussion, critique, planning.", usage: "Use when an idea is reasonable but misaligned.", whenNotToUse: "Avoid when quick yes/no decisions are needed.", tags: ["Expression", "feedback"] }),
  lesson({ id: "en-exam-concession", language: "English", contentType: "Exam", difficulty: "Upper-intermediate", title: "concession in argument", expression: "While convenience matters, trust is the real barrier.", translation: "便利性固然重要，但信任才是真正的障碍。", summary: "Useful for CET-style argument and real analysis.", explanation: "While introduces concession, then the main claim appears after the comma.", realContext: "Essays, reports, trend analysis.", usage: "Use to show balanced reasoning.", whenNotToUse: "Avoid if both sides are not genuinely relevant.", grammarPoints: ["While + clause, main claim"], tags: ["Exam", "argument"] }),

  lesson({ id: "ko-not-my-taste", language: "Korean", contentType: "Expression", difficulty: "TOPIK 2-3", title: "제 취향은 아니에요.", expression: "제 취향은 아니에요.", translation: "这不太是我的取向 / 不是我的菜。", summary: "A polite way to say something is not your taste.", explanation: "취향 includes taste, preference, and identity signal.", realContext: "Talking about music, fashion, design, food.", usage: "Use when you do not want to judge the thing as bad.", whenNotToUse: "Avoid when formal evaluation requires objective reasons.", words: [["취향", "taste, preference"]], aiNote: "Very useful for Korean pop culture because preference is often discussed as identity.", tags: ["Expression", "Culture"] }),
  lesson({ id: "ko-kind-of", language: "Korean", contentType: "Grammar", difficulty: "TOPIK 2-3", title: "-는 편이에요", expression: "저는 가사를 먼저 보는 편이에요.", translation: "我属于会先看歌词的类型。", summary: "A natural way to describe tendencies.", explanation: "-는 편이다 softens a habit into a general tendency.", realContext: "Interviews, self-introduction, fandom conversation.", usage: "Use when describing what you usually do.", whenNotToUse: "Avoid for one-time actions.", grammarPoints: ["verb/adjective + 편이다"], tags: ["Grammar", "TOPIK"] }),
  lesson({ id: "ko-internet-ㅇㅈ", language: "Korean", contentType: "Internet", difficulty: "Intermediate", title: "ㅇㅈ", expression: "이 비트 진짜 ㅇㅈ", translation: "这个 beat 真的认了 / 服。", summary: "Internet shorthand for 인정, meaning agreement or 인정한다.", explanation: "It is casual and compressed, common in comments.", realContext: "YouTube comments, livestream chat, social posts.", usage: "Use only in informal internet contexts.", whenNotToUse: "Avoid in exams, work, or polite conversation.", tags: ["Internet", "K-Hiphop"] }),
  lesson({ id: "ko-interview-solo", language: "Korean", contentType: "Interview", difficulty: "TOPIK 3", title: "솔직히 말하면", expression: "솔직히 말하면 부담이 있었어요.", translation: "老实说，当时有压力。", summary: "A common interview opener for honest reflection.", explanation: "솔직히 말하면 prepares the listener for a personal or candid answer.", realContext: "Artist interviews, documentaries, podcasts.", usage: "Use before a sincere admission.", whenNotToUse: "Avoid overusing it before ordinary facts.", tags: ["Interview", "Culture"] }),
  lesson({ id: "ko-lyric-vibe", language: "Korean", contentType: "Lyric", difficulty: "Intermediate", title: "분위기", expression: "이 곡은 분위기가 좋아요.", translation: "这首歌氛围很好。", summary: "A broad but useful word for vibe, mood, and atmosphere.", explanation: "분위기 can describe rooms, music, people, photos, and social situations.", realContext: "Music reactions, design comments, daily talk.", usage: "Use when the overall feeling matters more than one detail.", whenNotToUse: "Avoid when you need precise technical critique.", words: [["분위기", "atmosphere, mood, vibe"]], tags: ["Lyric", "Culture"] }),
  lesson({ id: "ko-daily-ㄹ까요", language: "Korean", contentType: "Grammar", difficulty: "TOPIK 2", title: "-ㄹ까요?", expression: "오늘은 이 앨범부터 들어볼까요?", translation: "今天要不要先听这张专辑？", summary: "A soft way to suggest doing something together.", explanation: "-ㄹ까요 asks or proposes, depending on context.", realContext: "Study plans, playlists, casual suggestions.", usage: "Use for gentle suggestions.", whenNotToUse: "Avoid when giving a firm instruction.", grammarPoints: ["verb stem + ㄹ/을까요"], tags: ["Grammar", "Daily"] }),
  lesson({ id: "ko-culture-nunchi", language: "Korean", contentType: "Culture", difficulty: "TOPIK 3", title: "눈치", expression: "눈치가 빠르다", translation: "有眼力见 / 很会察言观色。", summary: "A culture-specific word about reading the room.", explanation: "눈치 combines social awareness, timing, and sensitivity.", realContext: "Variety shows, workplace scenes, interviews.", usage: "Use for social perception.", whenNotToUse: "Avoid translating it as only eyesight or intelligence.", tags: ["Culture", "Nuance"] }),
  lesson({ id: "ko-exam-because", language: "Korean", contentType: "Exam", difficulty: "TOPIK 3", title: "-기 때문에", expression: "시간이 부족하기 때문에 계획이 필요해요.", translation: "因为时间不够，所以需要计划。", summary: "A formal cause structure useful for TOPIK writing.", explanation: "-기 때문에 is more written/formal than casual -아서/어서 in many contexts.", realContext: "TOPIK writing, reports, explanations.", usage: "Use for clear cause-effect reasoning.", whenNotToUse: "Avoid in very casual chat if it sounds too formal.", grammarPoints: ["verb/adjective + 기 때문에"], tags: ["Exam", "Grammar"] })
];

content.length = 0;
mvpContent.forEach(entry => content.push(entry));
languageLessons.english = mvpLessons.filter(entry => entry.language === "English");
languageLessons.korean = mvpLessons.filter(entry => entry.language === "Korean");
state.languageFilter = state.languageFilter || "All";
state.libraryFilter = state.libraryFilter || { page: "All", language: "All", tag: "All" };

function sourceMeta(entry) {
  if (!entry.sourceName && !entry.sourceUrl) return "";
  const details = [entry.sourceType, entry.author, entry.publishedAt].filter(Boolean).join(" &#183; ");
  return `<div class="source-meta">${details ? `<span>${details}</span>` : ""}${entry.sourceUrl ? `<a class="source-link" href="${entry.sourceUrl}" target="_blank" rel="noopener noreferrer">Source &#8599;</a>` : ""}</div>`;
}
function imageBlock(entry) {
  if (!entry.imageUrl || !entry.imageAlt || !entry.visualImportance) return "";
  const credit = entry.imageCredit || entry.imageSourceUrl ? `<figcaption>${entry.imageCredit || "Image source"}${entry.imageSourceUrl ? ` &#183; <a href="${entry.imageSourceUrl}" target="_blank" rel="noopener noreferrer">Image source &#8599;</a>` : ""}</figcaption>` : "";
  return `<figure class="content-image"><img src="${entry.imageUrl}" alt="${entry.imageAlt}" loading="lazy">${credit}</figure>`;
}
function tags(list) { return `<div class="tag-row">${(list || []).map(tag => `<button class="tag" type="button" data-topic="${tag}">${tag}</button>`).join("")}</div>`; }
function lessonTags(entry) { return tags([entry.contentType, entry.difficulty, ...(entry.tags || [])].filter(Boolean)); }
function getContent(id) { return content.find(entry => entry.id === id) || Object.values(languageLessons).flat().find(entry => entry.id === id); }
function renderToday() {
  const focus = content.find(entry => entry.contentType === "Focus");
  const fresh = content.filter(entry => entry.page === "today" && entry.contentType === "Fresh Find").slice(0, 2);
  const continueItems = [languageLessons.english[0], languageLessons.korean[0], content.find(entry => entry.page === "observe")];
  document.querySelector("#today").innerHTML = `<div class="today-editor-opening" aria-label="Editor's Opening"><span class="page-kicker">Editor's Opening</span><p id="today-title">今天，先看一件真正值得理解的事。</p></div><article class="today-focus" aria-label="Today's Focus"><div class="today-focus-copy"><span class="panel-label">Today's Focus</span><h1>${focus.title}</h1><p>${focus.summary}</p></div><div class="today-focus-aside"><span>Why it matters</span><p>${focus.aiNote}</p>${tags(focus.tags)}${actions(focus.id)}${sourceMeta(focus)}</div></article><section class="today-section" aria-label="Fresh Finds"><div class="today-section-heading"><span class="panel-label">Fresh Finds</span></div><div class="fresh-grid">${fresh.map(entry => `<article class="fresh-card">${imageBlock(entry)}<div class="fresh-card-body"><span class="card-meta">${entry.category} / ${entry.subCategory}</span><h3>${entry.title}</h3><p>${entry.summary}</p></div><div class="fresh-card-footer">${actions(entry.id)}${sourceMeta(entry)}</div></article>`).join("")}</div></section><section class="today-continue" aria-label="Continue Learning"><span class="panel-label">Continue Learning</span><div class="focus-list">${continueItems.map(entry => `<div class="focus-row"><strong>${entry.category || entry.language}</strong><span>${entry.title}</span></div>`).join("")}</div></section>`;
}
function renderObserve() {
  const filters = ["All", "Self-media", "Design", "K-Hiphop", "AI", "E-commerce"];
  const items = content.filter(entry => entry.page === "observe" && (state.observeFilter === "All" || entry.category === state.observeFilter));
  document.querySelector("#observe").innerHTML = `<span class="page-kicker">Observe</span><h1 id="observe-title" class="page-title">Observe, do not chase.</h1><p class="page-subtitle">25 contextual notes across self-media, design, K-Hiphop, AI, and e-commerce.</p><div class="toolbar">${filters.map(filter => `<button class="chip ${state.observeFilter === filter ? "active" : ""}" data-filter="${filter}">${filter}</button>`).join("")}</div><div class="content-grid">${items.map(observeCard).join("")}</div>`;
}
function observeCard(entry) { return `<article class="item-card observe-card">${imageBlock(entry)}<span class="card-meta">${entry.category} / ${entry.subCategory}</span><h3>${entry.title}</h3><p>${entry.summary}</p><div class="what-why"><span><strong>What:</strong> ${entry.what}</span><span><strong>Why:</strong> ${entry.why}</span><span><strong>Takeaway:</strong> ${entry.takeaway}</span></div>${entry.aiNote ? `<div class="editor-note"><span class="editor-mark"></span><p>${entry.aiNote}</p></div>` : ""}${tags(entry.tags)}${sourceMeta(entry)}${actions(entry.id)}</article>`; }
function renderLanguage() {
  const selected = state.languageTab === "korean" ? "Korean" : "English";
  const lessons = (selected === "English" ? languageLessons.english : languageLessons.korean).filter(entry => state.languageFilter === "All" || entry.contentType === state.languageFilter);
  const filterOptions = ["All", "Expression", "Grammar", "Internet", "Culture", "Exam"];
  document.querySelector("#language").innerHTML = `<span class="page-kicker">Language</span><h1 id="language-title" class="page-title">${selected}</h1><p class="page-subtitle">${selected === "English" ? "Natural expression, business nuance, grammar in context, and exam-ready argument." : "Intermediate Korean through daily use, interviews, lyrics, internet culture, and TOPIK grammar."}</p><div class="toolbar"><button class="chip ${state.languageTab === "english" ? "active" : ""}" data-language="english">English</button><button class="chip ${state.languageTab === "korean" ? "active" : ""}" data-language="korean">Korean</button></div><div class="toolbar">${filterOptions.map(filter => `<button class="chip ${state.languageFilter === filter ? "active" : ""}" data-language-filter="${filter}">${filter}</button>`).join("")}</div><div class="lesson-grid">${lessons.map(languageCard).join("")}</div>`;
}
function languageCard(entry) { return `<article class="lesson-card"><span class="card-meta">${entry.language} / ${entry.contentType} / ${entry.difficulty}</span><h3>${entry.title}</h3><div class="phrase">${entry.expression || entry.phrase}</div><p class="translation">${entry.translation}</p><p>${entry.summary}</p><div class="what-why"><span><strong>Context:</strong> ${entry.realContext}</span><span><strong>Usage:</strong> ${entry.usage}</span><span><strong>Do not use:</strong> ${entry.whenNotToUse}</span></div>${(entry.words || []).length ? `<div class="word-list">${entry.words.map(([word, desc]) => `<div class="word-row"><strong>${word}</strong><span>${desc}</span></div>`).join("")}</div>` : ""}${(entry.grammarPoints || []).length ? tags(entry.grammarPoints) : ""}<div class="editor-note"><span class="editor-mark"></span><p>${entry.aiNote}</p></div>${lessonTags(entry)}${sourceMeta(entry)}${actions(entry.id)}</article>`; }
function renderLibrary() {
  const saved = state.library.map(saved => ({ ...getContent(saved.id), savedAt: saved.savedAt })).filter(Boolean);
  const allTags = [...new Set(saved.flatMap(entry => entry.tags || []))].sort();
  const filtered = saved.filter(entry => (state.libraryFilter.page === "All" || entry.page === state.libraryFilter.page || entry.category === state.libraryFilter.page) && (state.libraryFilter.language === "All" || entry.language === state.libraryFilter.language) && (state.libraryFilter.tag === "All" || (entry.tags || []).includes(state.libraryFilter.tag)));
  document.querySelector("#library").innerHTML = `<span class="page-kicker">Library</span><h1 id="library-title" class="page-title">Saved knowledge, not just bookmarks.</h1><p class="page-subtitle">Saved items preserve tags, notes, preferences, source metadata, language, content type, and useful images.</p><div class="toolbar"><button class="chip ${state.libraryFilter.page === "All" ? "active" : ""}" data-library-page="All">All</button>${["today","observe","Language"].map(value => `<button class="chip ${state.libraryFilter.page === value ? "active" : ""}" data-library-page="${value}">${value}</button>`).join("")}</div><div class="toolbar"><button class="chip ${state.libraryFilter.language === "All" ? "active" : ""}" data-library-language="All">All languages</button><button class="chip ${state.libraryFilter.language === "English" ? "active" : ""}" data-library-language="English">English</button><button class="chip ${state.libraryFilter.language === "Korean" ? "active" : ""}" data-library-language="Korean">Korean</button></div><div class="toolbar"><button class="chip ${state.libraryFilter.tag === "All" ? "active" : ""}" data-library-tag="All">All tags</button>${allTags.map(tag => `<button class="chip ${state.libraryFilter.tag === tag ? "active" : ""}" data-library-tag="${tag}">${tag}</button>`).join("")}</div><div class="library-grid"><section>${filtered.length ? filtered.map(libraryCard).join("") : `<div class="empty-state">No saved items match this filter.</div>`}</section><aside class="panel"><span class="panel-label">Library State</span><div class="saved-count">${saved.length}</div><p class="card-copy">items saved locally</p><div class="focus-list"><div class="focus-row"><strong>Interested</strong><span>${countPreference("Interested")}</span></div><div class="focus-row"><strong>Not interested</strong><span>${countPreference("Not interested")}</span></div><div class="focus-row"><strong>Not my taste</strong><span>${countPreference("Not my taste")}</span></div></div></aside></div>`;
}
function libraryCard(entry) { const note = state.notes[entry.id] || ""; return `<article class="library-card" data-library-id="${entry.id}">${imageBlock(entry)}<span class="card-meta">${entry.page} / ${entry.category || entry.language} ${entry.contentType ? "/ " + entry.contentType : ""}</span><h3>${entry.title}</h3><p>${entry.summary}</p>${tags(entry.tags || [])}${sourceMeta(entry)}<textarea class="note-input" data-note-id="${entry.id}" placeholder="Add a short note or connection...">${note}</textarea><div class="actions"><button class="text-button" data-save-note="${entry.id}">Save note</button><button class="remove-button" data-remove="${entry.id}">Remove</button></div></article>`; }
function activateTopic(topic) { const map = { "self-media":"Self-media", "design":"Design", "packaging":"Design", "k-brand":"Design", "k-hiphop":"K-Hiphop", "culture":"K-Hiphop", "ai":"AI", "e-commerce":"E-commerce" }; state.observeFilter = map[String(topic).toLowerCase()] || "All"; localStorage.setItem(storageKeys.observeFilter, state.observeFilter); setPage("observe"); renderObserve(); bindActions(); }
function setLanguage(language) { state.languageTab = language; state.languageFilter = "All"; localStorage.setItem(storageKeys.languageTab, language); renderLanguage(); bindActions(); }
const baseBindActions = bindActions;
bindActions = function () { baseBindActions(); document.querySelectorAll("[data-topic]").forEach(button => button.addEventListener("click", () => activateTopic(button.dataset.topic))); document.querySelectorAll("[data-language-filter]").forEach(button => button.addEventListener("click", () => { state.languageFilter = button.dataset.languageFilter; renderLanguage(); bindActions(); })); document.querySelectorAll("[data-library-page]").forEach(button => button.addEventListener("click", () => { state.libraryFilter.page = button.dataset.libraryPage; renderLibrary(); bindActions(); })); document.querySelectorAll("[data-library-language]").forEach(button => button.addEventListener("click", () => { state.libraryFilter.language = button.dataset.libraryLanguage; renderLibrary(); bindActions(); })); document.querySelectorAll("[data-library-tag]").forEach(button => button.addEventListener("click", () => { state.libraryFilter.tag = button.dataset.libraryTag; renderLibrary(); bindActions(); })); };
render();
